const path = require('path');
const os = require('os');
const fs = require('fs-extra');
const { createFakeLibraries } = require('./librayGenerator');

const OUTPUT_PATH = path.join(os.tmpdir(), './autoGeneratedLibraries');

createFakeLibraries(OUTPUT_PATH);

// eslint-disable-next-line import/no-dynamic-require
require(path.join(OUTPUT_PATH, 'index.js'));

fs.removeSync(OUTPUT_PATH);
