const path = require('path');

const OUTPUT_PATH = path.join(__dirname, '../autoGeneratedLibraries');

// eslint-disable-next-line import/no-dynamic-require
require(path.join(OUTPUT_PATH, 'index.js'));
